// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package config

import (
	"encoding/json"

	"github.com/LemoFoundationLtd/lemochain-go/common/hexutil"
)

var _ = (*RpcMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (r RpcWS) MarshalJSON() ([]byte, error) {
	type RpcWS struct {
		Disable       bool           `json:"disable"`
		Port          hexutil.Uint32 `json:"port"`
		CorsDomain    string         `json:"corsDomain"`
		ListenAddress string         `json:"listenAddress"`
	}
	var enc RpcWS
	enc.Disable = r.Disable
	enc.Port = hexutil.Uint32(r.Port)
	enc.CorsDomain = r.CorsDomain
	enc.ListenAddress = r.ListenAddress
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (r *RpcWS) UnmarshalJSON(input []byte) error {
	type RpcWS struct {
		Disable       *bool           `json:"disable"`
		Port          *hexutil.Uint32 `json:"port"`
		CorsDomain    *string         `json:"corsDomain"`
		ListenAddress *string         `json:"listenAddress"`
	}
	var dec RpcWS
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Disable != nil {
		r.Disable = *dec.Disable
	}
	if dec.Port != nil {
		r.Port = uint32(*dec.Port)
	}
	if dec.CorsDomain != nil {
		r.CorsDomain = *dec.CorsDomain
	}
	if dec.ListenAddress != nil {
		r.ListenAddress = *dec.ListenAddress
	}
	return nil
}
